# Generated by Django 5.2.1 on 2025-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='roast',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
